### ISSUE TITLE
Multiple payments taken on submit

### ISSUE THREAD

**Issue by DesignByNeil** [RootStudio/Root-Perch-Shop-Omnipay-v3#11]
Hi Byron

Everything has been been working well since January, however I have had a couple of issues with multiple payments in recent weeks having been taken when a customer clicks the submit button.

I have checked and they haven't refreshed.

Have you any ideas what could be the cause of multiple payments?

Thanks

Neil

**Comment by byron-roots** [comment]
Hi Neil

I'm not aware of any issues with multiple payments. The payment flow for stripe intents is as follows.

1. A Payment intent is made, e.g 'A payment for £100 was created'. This is given a payment intent ID.
2. The payment intent is then used to create a charge, this either happens immediately if 3DS2 is not needed, or after the 3DS2 check is complete
3. The payment is then completed once the charge has been reconciled

If multiple payments are happening we would need to know which step it's happening. Are the payments all using the same pi_ ID, do they just share the same ch_ ID, or is there nothing in common but the purchase amounts and timeframes.

In the stripe dashboard under each payment there is an activity log which gives you detailed responses for each step of the payment journey.
![Screenshot 2021-03-16 at 09 41 44](https://user-images.githubusercontent.com/38127763/111288190-dcc4a780-863b-11eb-8fb6-cae18de16998.png)

As far as the cause, it might be that the redirect isn't completing correctly so it runs the charge again on complete page, or it redirects back to the initial payment page instead of complete page.

**Comment by DesignByNeil** [comment]
Thanks Byron

It is producing multiple orders in the perch interface but i will check what is happening within stripe.
